[project]
name = "mapc-mh"
version = "0.1.0"
description = "Trajectory-Based Metaheuristics for WiFi Multi-AP Coordination"

readme = "README.md"
license = {file = "LICENSE"}

authors = [
  {name = "Maksymilian Wojnar", email = "maksymilian.wojnar@agh.edu.pl"}
]

requires-python = ">=3.12"
dependencies = [
    "jax~=0.8.0",
    "matplotlib~=3.10.8",
    "numpy~=2.3.5",
    "optuna~=4.5.0",
    "scipy~=1.17.1",
    "tqdm~=4.67.3",
    "mapc-optimal-research@git+https://github.com/ml4wifi-devs/mapc-optimal-research",
]

[tool.setuptools.packages]
find = {}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
